[workspace]
members = [
    "lapex",
    "lapex-input",
    "lapex-automaton",
    "lapex-lexer",
    "lapex-parser",
    "lapex-codegen",
    "lapex-cpp-codegen",
    "lapex-rust-codegen",
    "lapex-input-gen"
]
exclude = [
    "generated/test_parser"
]