[package]
name = "lapex"
version = "0.1.0"
edition = "2021"

[dependencies]
lapex-lexer = { path = "../lapex-lexer" }
lapex-parser = { path = "../lapex-parser" }
lapex-input = { path = "../lapex-input" }
