[package]
name = "lapex-lexer"
version = "0.1.0"
edition = "2021"

[dependencies]
lapex-automaton = { path = "../lapex-automaton" }
lapex-input = { path = "../lapex-input" }
lapex-codegen = { path = "../lapex-codegen" }