[package]
name = "lapex-input-gen"
version = "0.1.0"
edition = "2021"

[build-dependencies]
lapex = { path = "../lapex" }
lapex-input-bootstrap = { path = "../lapex-input-bootstrap" }

[dependencies]
lapex-input = { path = "../lapex-input" }
regex-syntax = "0.7.4"